# Ingress resource for the application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-go-webapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my-go-webapp.local
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-go-webapp
            port:
              number: 80